language: java
os: linux
dist: xenial
jdk:
    - oraclejdk11
addons:
    sonarcloud:
        organization: "sshanks-kx"
        token: "$SONAR_KEY"
script:
    - mvn clean verify sonar:sonar -Dsonar.projectKey=sshanks-kx_testjava